### ISSUE TITLE
Full Screen No Longer Works on FFXIV with wine-tkg

### ISSUE THREAD

**Issue by sangoku116** [Frogging-Family/wine-tkg-git#338]
Fullscreen used to work on FFXIV, but now compiled with the latest master, it crashes when changing to fullscreen. Borderless windowed and windowed work as expected.  Here are the logs:
`XIO:  fatal IO error 9 (Bad file descriptor) on X server ":0.0"
      after 245 requests (244 known processed) with 0 events remaining.
WARNING: radv is not a conformant vulkan implementation, testing use only.
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  10 (X_UnmapWindow)
  Resource id in failed request:  0x8e00003
  Serial number of failed request:  22090
  Current serial number in output stream:  22127
Monitored process exited.
All monitored processes have exited.
Exit with returncode 0`

**Comment by Tk-Glitch** [comment]
Should be fixed with https://github.com/Frogging-Family/wine-tkg-git/commit/211341c5ebb427c6aad555dc7bdb228308b939e9

**Comment by sangoku116** [comment]
It is still crashing with the same error.

**Comment by Tk-Glitch** [comment]
![Screenshot_20210418_222657](https://user-images.githubusercontent.com/741977/115159819-426dde80-a095-11eb-83d5-88a6bca2a4d7.png)
![Screenshot_20210418_232419](https://user-images.githubusercontent.com/741977/115161307-4140af80-a09d-11eb-97b7-dfc297520bc3.png)
I cannot reproduce the issue on my end.

**Comment by sangoku116** [comment]
No issues with proton. Made a new prefix and reinstalled the game, still the same issue the logs: 
`XIO:  fatal IO error 9 (Bad file descriptor) on X server ":0.0"
      after 254 requests (253 known processed) with 0 events remaining.
err:   DXGI: ResizeTarget: Failed to query containing output
info:  Setting display mode: 1280x720@60
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  10 (X_UnmapWindow)
  Resource id in failed request:  0xa200003
  Serial number of failed request:  3834
  Current serial number in output stream:  3847
Monitored process exited.
All monitored processes have exited.
Exit with returncode 0
`

**Comment by Tk-Glitch** [comment]
Are you using Wayland (and as a result, XWayland for the game)? There are reported issues upstream regarding XWayland and fullscreen.

**Comment by sangoku116** [comment]
> Are you using Wayland (and as a result, XWayland for the game)? There are reported issues upstream regarding XWayland and fullscreen.

I am not, I'm using X. No issues with Titanfall 2 and WOW
