### ISSUE TITLE
Stil doesn't work with elder scroll online

### ISSUE THREAD

**Issue by psychaos999** [Frogging-Family/wine-tkg-git#759]
Hi,
it already months that wine/proton tkg die when try to start Elder Scroll Online.
This issue has been fixed by GE version many many versions ago.

I know I can use GE and shut up, but maybe this ticket could be useful to fix other things tied to this problem
I attached a minimal log.

Regards
[eso.log](https://github.com/Frogging-Family/wine-tkg-git/files/8592248/eso.log)

**Comment by Tk-Glitch** [comment]
If we're talking about the crash after clicking play, it crashes the same way on plain wine-staging with zero external patch, so that doesn't look like a tkg issue. GE has moved to using proton 7.0 wine tree instead of upstream, and it's likely why it works there (as he hasn't done anything for TESO support in his wine build).

You can build proton-tkg/wine-tkg using Valve's tree if desired (using the `_custom_wine_source=""` option for wine, or using the `_LOCAL_PRESET="valve"` preset for proton (or one of its variants for experimental or bleeding edge, see proton-tkg.cfg for details)).

**Comment by Tk-Glitch** [comment]
https://bugs.winehq.org/show_bug.cgi?id=51976

**Comment by Bananaman** [comment]
@Tk-Glitch Hi Etienne, thanks for finding and linking to that upstream bug report!

I've been covering the issue at https://github.com/bottlesdevs/wine/issues/31 too, which is a build of Wine-TKG named "Caffe" (it's TKG with a custom config).

The info I can bring to the table is the following:

- A fix has existed in Wine-GE aka Lutris-GE since [Wine-6.20-GE-1](https://github.com/GloriousEggroll/wine-ge-custom/releases/tag/6.20-GE-1) or earlier ([this is the first fixed Wine version the community pointed to](https://forums.elderscrollsonline.com/en/discussion/590187/eso-7-2-5-patch-completely-broke-on-linux-unsupported) but it may be actually fixed by some earlier release). That means the fix existed at/before October 2021.
- The discussion you linked to has a great comment which seems to have identified the exact patches that fix it: https://bugs.winehq.org/show_bug.cgi?id=51976#c12

**Comment by Tk-Glitch** [comment]
> @Tk-Glitch Hi Etienne, thanks for finding and linking to that upstream bug report!
> 
> I've been covering the issue at [bottlesdevs/wine#31](https://github.com/bottlesdevs/wine/issues/31) too, which is a build of Wine-TKG named "Caffe" (it's TKG with a [custom config](https://raw.githubusercontent.com/bottlesdevs/build-tools/main/runners/vaniglia/wine-tkg.cfg)).
> 
> The info I can bring to the table is the following:
> 
> * A fix has existed in Wine-GE aka Lutris-GE since [Wine-6.20-GE-1](https://github.com/GloriousEggroll/wine-ge-custom/releases/tag/6.20-GE-1) or earlier ([this is the first fixed Wine version the community pointed to](https://forums.elderscrollsonline.com/en/discussion/590187/eso-7-2-5-patch-completely-broke-on-linux-unsupported) but it may be actually fixed by some earlier release). That means the fix existed at/before October 2021.
> * The discussion you linked to has a great comment which seems to have identified the exact patches that fix it (edit: I just noticed that the guy still runs into a black screen afterwards, sadly): https://bugs.winehq.org/show_bug.cgi?id=51976#c12

Sadly we have those already and it seemingly doesn't fix the issue on any recent version of wine, so newer upstream changes must have broken that further. I'm thinking about moving Proton-tkg to using valve tree by default (using our exp-bleeding profile), so the issue shouldn't exist there at least, but of course that doesn't help us upstream.
