### ISSUE TITLE
[Proton-tkg] ERROR: Patch application has failed.

### ISSUE THREAD

**Issue by Kerrung** [Frogging-Family/wine-tkg-git#765]
eebc155 
[last_build_config.log](https://github.com/Frogging-Family/wine-tkg-git/files/8659706/last_build_config.log)
[prepare.log](https://github.com/Frogging-Family/wine-tkg-git/files/8659707/prepare.log)
![Screenshot from 2022-05-10 13-25-25](https://user-images.githubusercontent.com/36989404/167583959-b90aa4f6-b334-42e0-b5ec-ba847b6a9c4b.png)

**Comment by Kerrung** [comment]
This is still valid using 99dbb65

**Comment by Tk-Glitch** [comment]
Should be fixed with https://github.com/Frogging-Family/wine-tkg-git/commit/3e33f08c5575c099a01da6b70832858a7b57454c

**Comment by Tk-Glitch** [comment]
Do you have `CUSTOM_MINGW_PATH` or `CUSTOM_GCC_PATH` set?

**Comment by Kerrung** [comment]
> Do you have `CUSTOM_MINGW_PATH` or `CUSTOM_GCC_PATH` set?

No. I can give you my cfg if you want

**Comment by Kerrung** [comment]
> [proton-tkg.cfg.zip](https://github.com/Frogging-Family/wine-tkg-git/files/8664122/proton-tkg.cfg.zip)

Are there any errors in my cfg? Is everything OK in it?

**Comment by Kerrung** [comment]
Still not working with f60ce7f with exactly the same error message as last time at https://github.com/Frogging-Family/wine-tkg-git/issues/765#issuecomment-1122726878

**Comment by Kerrung** [comment]
2405b9e
[last_build_config.log](https://github.com/Frogging-Family/wine-tkg-git/files/8694362/last_build_config.log)
[prepare.log](https://github.com/Frogging-Family/wine-tkg-git/files/8694363/prepare.log)
![Screenshot from 2022-05-15 10-30-03](https://user-images.githubusercontent.com/36989404/168458653-a7f1ea83-7c11-4db6-bcae-9e3e6d651b76.png)

**Comment by Tk-Glitch** [comment]
> > [proton-tkg.cfg.zip](https://github.com/Frogging-Family/wine-tkg-git/files/8664122/proton-tkg.cfg.zip)
> 
> Are there any errors in my cfg? Is everything OK in it?

Yes your config is broken. You have added `-march=native,` to your _LD_FLAGS and _CROSS_LD_FLAGS, which is incorrect.

**Comment by Tk-Glitch** [comment]
The initial issue is fixed, and the config error is on the user side. Closing.
